### ISSUE TITLE
Twitter Bootstrap support

### ISSUE THREAD

**Issue by akrohn** [shellscape/Brew#3]
Hello, nice work and approach.

I would love to see support for Bootstrap javascript controls for a consistent ui in projects using Bootstrap.

Cheers.

**Comment by shellscape** [comment]
I looked into Bootstrap, and it doesn't look like any of the ui components provide events (please correct me if I'm wrong, I just browsed their demo site) - events are the main draw for the webforms components. So if I follow your suggestion, you'd like to see this supported so that you can render bootstrap components to the page with server tags?

Thanks for the compliments.

edit:

I stand corrected. I found a reference to events on the overview at http://twitter.github.com/bootstrap/javascript.html but I can't find any documentation on those events. Documentation would be key to supporting it.

**Comment by akrohn** [comment]
Yeah you are right. Documentation on JQuery UI API is much more complete. 

Yes. It would be great to see webforms server side support for Bootstrap javascript controls. Don't know if this wish belongs here because this project focuses on JQuery UI.

**Comment by shellscape** [comment]
It looks like bootstrap piggybacks on jQuery (or is at least very similar) so I don't think it's outside of the realm of possibility for Brew. It looks like a solid candidate. One of the things I did with Brew was to increase the separation between the core function and the different "engines" (eg. Webforms, MVC). So I could probably fit it in. I'd definitely need some documentation to work from. Going through the code for bootstrap to generate all of the classes for Brew would be crazy time consuming.

**Comment by shellscape** [comment]
Closing this for now. I've not been able to get anywhere with Twitter Support or the Bootstrap team with regard to comprehensive documentation. Please re-open should that change.
